---
title: "SDG network ms"
author: "Peter Søgaard Jørgensen"
date: "4 July 2015"
output:
  html_document:
    number_sections: yes
    theme: default
    toc: yes
    toc_depth: 3
  md_document:
    dev: png
    toc: yes
    toc_depth: 3
  pdf_document:
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 3
  word_document:
    reference_docx: template.docx
category: SDGs
layout: post
tagline: "a system of targets"
tags:
- outline
- SDGs
- network analysis
- sustainability science
- sustainable development
- systems science
bibliography: PostDocKVA2.bib
---
{% include JB/setup %}



# Intro

## The SDGS

In September 2015 the worlds governments will agree on a set of global goals for sutainable development of humanity and the environment, the Sustainable Development Goals (SDGs). The SDGs can be seen as following up on international efforts to set goals for how humanity can continue to prosper while staying within a flurising environment on which we as a species ultimately depend. In the UN system this effort dates back to 1972 and the Stockholm Convention and 198x with the Brundtland report and the Earth summit in Rio de Janeiro in 1992. From 2000 to 2015 the Millennium Development Goals have been the main framework for this effort.

The SDGs differ from previous sustainable development goals in the UN system in a number of ways. First, by targeting both develloping and developed countries. By having been negotiated in a comprehsive and fairly open process, involving many expert group. And finaly, through this process the SDGs have become very comprehensive and cover 17 topics spanning from XX to XX with 169 targets in total.

Insert latest update on the SDG negotiation process and prediction of outcome.

## The SDGs as a complex networked system of targets

Thus, the SDGs can be seen as a system of goals and their targets with connected by their content.


## The importance of formal analysis and visualization to understand the network

The complexity of the SDGs provides a challenge to understand how the entientis of the system of targets work together. Furthermore, it is a challenge to visualize how the system is connected.


## Previous system approaches to the SDGs

Previous analysis of the SDGs have taken a couple of different approaches. While some have taken a system based vie and seen them as a network of targets connected through the content of their goalsk other studies have anlyzed the conent of each goal, based on its targets. 


## What do we do here

In this study we seek to complement previous stdueies, by taking a similar but different approach that views the SDG s as a network of targets connected by their properties. We analyze the targets with regard to two main properties the actions and aims proposed and the subjects of the target. We take a keyword based approach to the analysis which allow a formal network analysis.

## What might a network analysis reveal?

A network analysis can reveal which targets are depdent on one another and what properties are important in connecting the targets.

In particular, a network based analsis may also reveal and help visualize clusters of of tartgets and goals that may need to be achieved together. Similarly, a network analysis can reveal topics that are isolated. Thus a network analysis will help understand how integrate the SDGs are or whether targets cluster together in groups that focus on e.g. enviornmental, economic or social aspects. This may be important becuase xyz.



# Methods

## Data material

We analyzed the draft targets as circulated to All Permanent Representatives and Permanent Observers to the United Nations New York in the zero draft of the post 2015 outcome document entitled "Transforming our World by 2030 - a New Agenda for Global Action" on July 2nd 2015 in letter by *Sam K. Kutesa*  on behalf of the Co-Facilitators of the intergovernmental negotiations on the post-2015 development agenda *Macharia Kamau* Permanent Representative Permanent Mission of the Republic of Kenya to the United Nations and *David Donoghue* Permanent Representative Permanent Mission of Ireland to the United Nations. The circulated draft included a number of proposed revisions to the zero draft targets. While we use the targets as circulated on June 2, we conduct supplementary to test the sensitivity of the results to the inclusio of those proposed revisions. 



