---
title: "SDG network ms - raw methods"
author: "Peter Søgaard Jørgensen"
date: "4 July 2015"
output:
  html_document:
    number_sections: yes
    theme: default
    toc: yes
    toc_depth: 3
  md_document:
    dev: png
    toc: yes
    toc_depth: 3
  pdf_document:
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 3
  word_document:
    reference_docx: template.docx
category: SDGs
layout: post
tagline: "a system of targets"
tags:
- outline
- SDGs
- network analysis
- sustainability science
- sustainable development
- systems science
bibliography: PostDocKVA2.bib
---
{% include JB/setup %}


* Next identify goals which need new keyword scoring from the zero outcome draft.
    * Then identify goals which would need new scoring from the prooposed revisions to the zero outcome draft.



# Methods

## Data material

We analyzed the draft targets as circulated to All Permanent Representatives and Permanent Observers to the United Nations New York in the zero draft of the post 2015 outcome document entitled "Transforming our World by 2030 - a New Agenda for Global Action" on July 2nd 2015 in letter by *Sam K. Kutesa*  on behalf of the Co-Facilitators of the intergovernmental negotiations on the post-2015 development agenda *Macharia Kamau* Permanent Representative Permanent Mission of the Republic of Kenya to the United Nations and *David Donoghue* Permanent Representative Permanent Mission of Ireland to the United Nations. The circulated draft included a number of proposed revisions to the zero draft targets. While we use the targets as circulated on June 2, we conduct supplementary to test the sensitivity of the results to the inclusio of those proposed revisions. 



